Foreground yes
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
MaxFileSize 250M
MaxScanSize 250M
StreamMaxLength 250M
AlertEncrypted yes
AlertExceedsMax yes
LogTime yes
