import { afterAll, describe, expect, it } from 'vitest';
import { eq, inArray } from 'drizzle-orm';
import { Database } from '../src/infrastructure/database/database.js';
import { accounts, folders, memberships, operationReceipts, projectResources, projects, resources, resourceVersions, users } from '../src/infrastructure/database/schema.js';
import { AccountService } from '../src/modules/account/account.service.js';
import { ImpactService } from '../src/modules/lifecycle/impact.service.js';
import { OrganizationService } from '../src/modules/projects/organization.service.js';
import { ProjectService } from '../src/modules/projects/project.service.js';
import { NoteService } from '../src/modules/resources/note.service.js';

const integration = describe.runIf(Boolean(process.env.DATABASE_URL));
integration('impacto y ciclo de vida con PostgreSQL', () => {
  const database = new Database(); const accountsService = new AccountService(database); const notes = new NoteService(database); const projectService = new ProjectService(database); const organization = new OrganizationService(database); const impacts = new ImpactService(database); const clerkId = `impact_owner_${crypto.randomUUID()}`; const ids: { user?: string; account?: string; resources: string[]; projects: string[] } = { resources: [], projects: [] };
  afterAll(async () => { if (ids.account) await database.db.delete(operationReceipts).where(eq(operationReceipts.accountId, ids.account)); if (ids.projects.length) { await database.db.delete(projectResources).where(inArray(projectResources.projectId, ids.projects)); await database.db.delete(folders).where(inArray(folders.projectId, ids.projects)); await database.db.delete(projects).where(inArray(projects.id, ids.projects)); } if (ids.resources.length) { await database.db.update(resources).set({ currentVersionId: null }).where(inArray(resources.id, ids.resources)); await database.db.delete(resourceVersions).where(inArray(resourceVersions.resourceId, ids.resources)); await database.db.delete(resources).where(inArray(resources.id, ids.resources)); } if (ids.user) { await database.db.delete(memberships).where(eq(memberships.userId, ids.user)); await database.db.delete(accounts).where(eq(accounts.personalOwnerUserId, ids.user)); await database.db.delete(users).where(eq(users.id, ids.user)); } await database.onModuleDestroy(); }, 30_000);
  it('recomienda archivar, detecta cambios e idempotencia y conserva recursos al borrar un proyecto', async () => {
    const identity = await accountsService.ensureLocalUser({ clerkUserId: clerkId }); ids.user = identity.user.id; ids.account = identity.account.id; const note = await notes.create(identity.account.id, identity.user.id, { title: 'Fuente central', content: 'Texto' }); ids.resources.push(note.id); const project = await projectService.create(identity.account.id, 'Proyecto A'); ids.projects.push(project.id); await organization.addResources(identity.account.id, project.id, [note.id]);
    const blocked = await impacts.get(identity.account.id, 'resource', note.id, 'delete'); expect(blocked.deletionAllowed).toBe(false); expect(blocked.recommendedAction).toBe('archive'); expect(blocked.locations).toContain('Proyecto A');
    const archive = await impacts.get(identity.account.id, 'resource', note.id, 'archive'); const key = crypto.randomUUID(); const archived = await impacts.execute(identity.account.id, 'resource', note.id, { action: 'archive', impactVersion: archive.impactVersion, confirmation: archive.confirmationPhrase, idempotencyKey: key }); expect(archived.state).toBe('archived'); await expect(impacts.execute(identity.account.id, 'resource', note.id, { action: 'archive', impactVersion: archive.impactVersion, confirmation: archive.confirmationPhrase, idempotencyKey: key })).resolves.toEqual(archived);
    const second = await notes.create(identity.account.id, identity.user.id, { title: 'Temporal', content: '' }); ids.resources.push(second.id); const stale = await impacts.get(identity.account.id, 'resource', second.id, 'delete'); await organization.addResources(identity.account.id, project.id, [second.id]); await expect(impacts.execute(identity.account.id, 'resource', second.id, { action: 'delete', impactVersion: stale.impactVersion, confirmation: stale.confirmationPhrase, idempotencyKey: crypto.randomUUID() })).rejects.toThrow('impacto cambió');
    const projectImpact = await impacts.get(identity.account.id, 'project', project.id, 'delete'); await impacts.execute(identity.account.id, 'project', project.id, { action: 'delete', impactVersion: projectImpact.impactVersion, confirmation: projectImpact.confirmationPhrase, idempotencyKey: crypto.randomUUID() }); await expect(projectService.get(identity.account.id, project.id)).rejects.toThrow('Proyecto no encontrado'); const [preserved] = await database.db.select({ deletedAt: resources.deletedAt }).from(resources).where(eq(resources.id, note.id)); expect(preserved?.deletedAt).toBeNull();
  }, 30_000);
});
