import { createHash } from 'node:crypto';
import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { and, eq, isNull, sql } from 'drizzle-orm';
import { Database } from '../../infrastructure/database/database.js';
import { withSerializationRetry } from '../../infrastructure/database/serialization-retry.js';
import { diagrams, folders, operationReceipts, projectResources, projects, relations, resources } from '../../infrastructure/database/schema.js';

export type ImpactEntityType = 'resource' | 'project' | 'folder' | 'diagram' | 'relation';
export type ImpactAction = 'archive' | 'delete';
type Executor = Pick<Database['db'], 'select' | 'update' | 'insert'>;
export interface Impact { entityType: ImpactEntityType; entityId: string; entityName: string; action: ImpactAction; state: string; affected: { projects: number; folders: number; resources: number; placements: number }; locations: string[]; consequences: string[]; recommendedAction: 'archive' | null; deletionAllowed: boolean; confirmationPhrase: string; impactVersion: string }

const version = (value: Omit<Impact, 'impactVersion'>) => createHash('sha256').update(JSON.stringify(value)).digest('base64url');
const withVersion = (value: Omit<Impact, 'impactVersion'>): Impact => ({ ...value, impactVersion: version(value) });

@Injectable()
export class ImpactService {
  constructor(@Inject(Database) private readonly database: Database) {}

  private async calculate(executor: Executor, accountId: string, entityType: ImpactEntityType, id: string, action: ImpactAction): Promise<Impact> {
    if (entityType === 'relation') {
      const [relation] = await executor.select({ label: relations.label, typeKey: relations.typeKey, sourceResourceId: relations.sourceResourceId, targetResourceId: relations.targetResourceId, archivedAt: relations.archivedAt }).from(relations).where(and(eq(relations.id, id), eq(relations.accountId, accountId), isNull(relations.deletedAt))).limit(1);
      if (!relation) throw new NotFoundException('Relación no encontrada.');
      const uses = await executor.select({ id: diagrams.id, name: diagrams.name, revision: diagrams.revision, archivedAt: diagrams.archivedAt, deletedAt: diagrams.deletedAt, projectId: projects.id, projectName: projects.name, projectDeletedAt: projects.deletedAt, document: diagrams.document }).from(diagrams).innerJoin(projects, and(eq(projects.id, diagrams.projectId), eq(projects.accountId, accountId))).where(sql`${diagrams.document} @> ${JSON.stringify({ edges: [{ data: { relationId: id } }] })}::jsonb`);
      const locations = uses.flatMap(item => item.document.edges.filter(edge => (edge as { data?: { relationId?: string } }).data?.relationId === id).map(edge => `${item.projectName} / ${item.name}${item.deletedAt || item.projectDeletedAt ? ' (recuperable)' : item.archivedAt ? ' (archivado)' : ''} · línea ${(edge as { id?: string }).id ?? '?'}`)).sort();
      const endpoints = await executor.select({ id: resources.id, title: resources.title }).from(resources).where(and(eq(resources.accountId, accountId), sql`${resources.id} in (${relation.sourceResourceId}, ${relation.targetResourceId})`));
      const source = endpoints.find(item => item.id === relation.sourceResourceId)?.title ?? 'Recurso';
      const target = endpoints.find(item => item.id === relation.targetResourceId)?.title ?? 'Recurso';
      const entityName = relation.label || `${source} — ${target}`;
      const deletionAllowed = locations.length === 0;
      return withVersion({ entityType, entityId: id, entityName, action, state: relation.archivedAt ? 'archived' : 'active', affected: { projects: new Set(uses.map(item => item.projectId)).size, folders: 0, resources: 2, placements: locations.length }, locations, consequences: action === 'archive' ? ['La Relación quedará archivada y sus visualizaciones existentes conservarán su identidad, explicación y evidencia.', 'No aparecerá para añadirla a otros Diagramas hasta restaurarla.'] : deletionAllowed ? ['La Relación saldrá de la Cuenta activa y quedará recuperable durante 30 días.'] : ['Esta Relación sigue representada en Diagramas.', 'Quita primero todas sus visualizaciones o archívala para conservarlas.'], recommendedAction: action === 'delete' && !deletionAllowed ? 'archive' : null, deletionAllowed, confirmationPhrase: `${action === 'delete' ? 'ELIMINAR' : 'ARCHIVAR'} ${entityName}` });
    }
    if (entityType === 'resource') {
      const [resource] = await executor.select({ id: resources.id, title: resources.title, archivedAt: resources.archivedAt }).from(resources).where(and(eq(resources.id, id), eq(resources.accountId, accountId), isNull(resources.deletedAt))).limit(1);
      if (!resource) throw new NotFoundException('Recurso no encontrado.');
      const placements = await executor.select({ id: projectResources.id, projectId: projects.id, projectName: projects.name, folderName: folders.name }).from(projectResources).innerJoin(projects, and(eq(projects.id, projectResources.projectId), eq(projects.accountId, accountId), isNull(projects.deletedAt))).leftJoin(folders, eq(folders.id, projectResources.folderId)).where(eq(projectResources.resourceId, id));
      const diagramUses = await executor.select({ projectId: projects.id, projectName: projects.name, diagramName: diagrams.name, document: diagrams.document }).from(diagrams).innerJoin(projects, and(eq(projects.id, diagrams.projectId), eq(projects.accountId, accountId), isNull(projects.deletedAt))).where(and(isNull(diagrams.deletedAt), sql`${diagrams.document} @> ${JSON.stringify({ nodes: [{ data: { resourceId: id } }] })}::jsonb`));
      placements.sort((a, b) => a.id.localeCompare(b.id)); diagramUses.sort((a, b) => a.diagramName.localeCompare(b.diagramName));
      const diagramCount = diagramUses.reduce((count, item) => count + item.document.nodes.filter(node => (node as { data?: { resourceId?: string } }).data?.resourceId === id).length, 0);
      const projectCount = new Set([...placements.map(item => item.projectId), ...diagramUses.map(item => item.projectId)]).size;
      const locations = [...placements.map(item => `${item.projectName}${item.folderName ? ` / ${item.folderName}` : ''}`), ...diagramUses.map(item => `${item.projectName} / ${item.diagramName}`)];
      const totalUses = placements.length + diagramCount; const deletionAllowed = totalUses === 0;
      const value: Omit<Impact, 'impactVersion'> = { entityType, entityId: id, entityName: resource.title, action, state: resource.archivedAt ? 'archived' : 'active', affected: { projects: projectCount, folders: new Set(placements.map(item => item.folderName).filter(Boolean)).size, resources: 1, placements: totalUses }, locations, consequences: action === 'archive' ? ['El Recurso dejará de aparecer en la Biblioteca activa.', totalUses ? 'Sus usos existentes conservarán la identidad y mostrarán que está archivado.' : 'Podrás restaurarlo durante la retención.'] : deletionAllowed ? ['El Recurso desaparecerá de los sistemas activos y quedará recuperable durante 30 días.'] : ['Sus referencias en Proyectos o Diagramas dejarían de funcionar.', 'Archívalo para conservar sus usos existentes.'], recommendedAction: action === 'delete' && !deletionAllowed ? 'archive' : null, deletionAllowed, confirmationPhrase: `${action === 'delete' ? 'ELIMINAR' : 'ARCHIVAR'} ${resource.title}` };
      return withVersion(value);
    }
    if (entityType === 'project') {
      const [project] = await executor.select({ id: projects.id, name: projects.name, archivedAt: projects.archivedAt }).from(projects).where(and(eq(projects.id, id), eq(projects.accountId, accountId), isNull(projects.deletedAt))).limit(1);
      if (!project) throw new NotFoundException('Proyecto no encontrado.');
      const folderRows = await executor.select({ id: folders.id }).from(folders).where(eq(folders.projectId, id)); const placements = await executor.select({ id: projectResources.id, resourceId: projectResources.resourceId }).from(projectResources).where(eq(projectResources.projectId, id));
      const diagramRows = await executor.select({ document: diagrams.document }).from(diagrams).where(and(eq(diagrams.projectId, id), isNull(diagrams.deletedAt)));
      const visualIds = diagramRows.flatMap(item => item.document.nodes.map(node => (node as { data?: { resourceId?: unknown } }).data?.resourceId).filter((value): value is string => typeof value === 'string'));
      const value: Omit<Impact, 'impactVersion'> = { entityType, entityId: id, entityName: project.name, action, state: project.archivedAt ? 'archived' : 'active', affected: { projects: 1, folders: folderRows.length, resources: new Set([...placements.map(item => item.resourceId), ...visualIds]).size, placements: placements.length + visualIds.length }, locations: [], consequences: action === 'archive' ? ['El Proyecto dejará de aparecer entre los activos y podrá restaurarse.'] : ['El Proyecto y su organización desaparecerán de los sistemas activos durante 30 días.', 'Los Recursos canónicos permanecerán intactos en la Biblioteca y otros Proyectos.'], recommendedAction: null, deletionAllowed: true, confirmationPhrase: `${action === 'delete' ? 'ELIMINAR' : 'ARCHIVAR'} ${project.name}` };
      return withVersion(value);
    }
    if (entityType === 'diagram') {
      const [diagram] = await executor.select({ name: diagrams.name, document: diagrams.document, archivedAt: diagrams.archivedAt, projectName: projects.name }).from(diagrams).innerJoin(projects, and(eq(projects.id, diagrams.projectId), eq(projects.accountId, accountId), isNull(projects.deletedAt))).where(and(eq(diagrams.id, id), isNull(diagrams.deletedAt))).limit(1);
      if (!diagram) throw new NotFoundException('Diagrama no encontrado.');
      const nodes = (Array.isArray(diagram.document?.nodes) ? diagram.document.nodes : []) as Array<{ data?: { resourceId?: unknown } }>;
      const resourceIds = new Set(nodes.map(node => typeof node?.data?.resourceId === 'string' ? node.data.resourceId : null).filter(Boolean));
      return withVersion({ entityType, entityId: id, entityName: diagram.name, action, state: diagram.archivedAt ? 'archived' : 'active', affected: { projects: 1, folders: 0, resources: resourceIds.size, placements: nodes.length }, locations: [diagram.projectName], consequences: action === 'archive' ? ['El Diagrama dejará de aparecer en la navegación activa y podrá restaurarse.', 'Los Recursos canónicos permanecerán intactos.'] : ['El Diagrama desaparecerá de los sistemas activos y quedará recuperable durante 30 días.', 'Los Recursos canónicos permanecerán intactos en la Biblioteca y otros Diagramas.'], recommendedAction: null, deletionAllowed: true, confirmationPhrase: `${action === 'delete' ? 'ELIMINAR' : 'ARCHIVAR'} ${diagram.name}` });
    }
    const [folder] = await executor.select({ id: folders.id, name: folders.name, archivedAt: folders.archivedAt }).from(folders).innerJoin(projects, and(eq(projects.id, folders.projectId), eq(projects.accountId, accountId), isNull(projects.deletedAt))).where(eq(folders.id, id)).limit(1);
    if (!folder) throw new NotFoundException('Carpeta no encontrada.');
    const placements = await executor.select({ id: projectResources.id }).from(projectResources).where(eq(projectResources.folderId, id)); const children = await executor.select({ id: folders.id }).from(folders).where(eq(folders.parentFolderId, id)); const deletionAllowed = false;
    return withVersion({ entityType, entityId: id, entityName: folder.name, action, state: folder.archivedAt ? 'archived' : 'active', affected: { projects: 1, folders: 1 + children.length, resources: placements.length, placements: placements.length }, locations: [], consequences: action === 'archive' ? ['La Carpeta dejará de aparecer en la organización activa y podrá restaurarse.', 'Los Recursos canónicos no se modifican.'] : ['La eliminación definitiva de Carpetas no está habilitada; archívala para conservar su organización.'], recommendedAction: action === 'delete' ? 'archive' : null, deletionAllowed, confirmationPhrase: `${action === 'delete' ? 'ELIMINAR' : 'ARCHIVAR'} ${folder.name}` });
  }

  async get(accountId: string, entityType: ImpactEntityType, id: string, action: ImpactAction) { if (!['resource', 'project', 'folder', 'diagram', 'relation'].includes(entityType) || !['archive', 'delete'].includes(action)) throw new BadRequestException('La entidad o acción no es válida.'); return this.calculate(this.database.db, accountId, entityType, id, action); }

  async execute(accountId: string, entityType: ImpactEntityType, id: string, input: { action?: unknown; impactVersion?: unknown; confirmation?: unknown; idempotencyKey?: unknown }) {
    if (!['resource', 'project', 'folder', 'diagram', 'relation'].includes(entityType)) throw new BadRequestException('La entidad no es válida.'); const action = input.action; if (action !== 'archive' && action !== 'delete') throw new BadRequestException('La acción no es válida.'); if (typeof input.idempotencyKey !== 'string' || !input.idempotencyKey.trim() || input.idempotencyKey.length > 120) throw new BadRequestException('Falta la clave de idempotencia.');
    return withSerializationRetry(() => this.database.db.transaction(async tx => {
      const [receipt] = await tx.select({ result: operationReceipts.result, entityType: operationReceipts.entityType, entityId: operationReceipts.entityId, action: operationReceipts.action }).from(operationReceipts).where(and(eq(operationReceipts.accountId, accountId), eq(operationReceipts.idempotencyKey, input.idempotencyKey as string))).limit(1); if (receipt) { if (receipt.entityType !== entityType || receipt.entityId !== id || receipt.action !== action) throw new ConflictException('La clave de idempotencia ya fue utilizada para otra operación.'); return receipt.result; }
      if (entityType === 'resource') await tx.select({ id: resources.id }).from(resources).where(and(eq(resources.id, id), eq(resources.accountId, accountId))).for('update'); else if (entityType === 'project') await tx.select({ id: projects.id }).from(projects).where(and(eq(projects.id, id), eq(projects.accountId, accountId))).for('update'); else if (entityType === 'diagram') await tx.select({ id: diagrams.id }).from(diagrams).innerJoin(projects, and(eq(projects.id, diagrams.projectId), eq(projects.accountId, accountId))).where(eq(diagrams.id, id)).for('update'); else if (entityType === 'relation') await tx.select({ id: relations.id }).from(relations).where(and(eq(relations.id, id), eq(relations.accountId, accountId))).for('update'); else await tx.select({ id: folders.id }).from(folders).innerJoin(projects, and(eq(projects.id, folders.projectId), eq(projects.accountId, accountId))).where(eq(folders.id, id)).for('update');
      const current = await this.calculate(tx, accountId, entityType, id, action); if (current.impactVersion !== input.impactVersion) throw new ConflictException({ message: 'El impacto cambió. Revísalo y confirma nuevamente.', details: { impact: current } }); if (input.confirmation !== current.confirmationPhrase) throw new BadRequestException('La confirmación escrita no coincide.'); if (action === 'delete' && !current.deletionAllowed) throw new BadRequestException('La eliminación no está habilitada para este impacto.');
      const now = new Date(); const purgeAfter = new Date(now.getTime() + 30 * 86_400_000); if (entityType === 'resource') await tx.update(resources).set(action === 'archive' ? { archivedAt: now, updatedAt: now } : { archivedAt: now, deletedAt: now, purgeAfter, updatedAt: now }).where(and(eq(resources.id, id), eq(resources.accountId, accountId))); else if (entityType === 'project') await tx.update(projects).set(action === 'archive' ? { archivedAt: now, updatedAt: now } : { archivedAt: now, deletedAt: now, purgeAfter, updatedAt: now }).where(and(eq(projects.id, id), eq(projects.accountId, accountId))); else if (entityType === 'diagram') await tx.update(diagrams).set(action === 'archive' ? { archivedAt: now, updatedAt: now } : { archivedAt: now, deletedAt: now, purgeAfter, updatedAt: now }).where(eq(diagrams.id, id)); else if (entityType === 'relation') await tx.update(relations).set(action === 'archive' ? { archivedAt: now, updatedAt: now, revision: sql`${relations.revision} + 1` } : { archivedAt: now, deletedAt: now, purgeAfter, updatedAt: now, revision: sql`${relations.revision} + 1` }).where(and(eq(relations.id, id), eq(relations.accountId, accountId))); else await tx.update(folders).set({ archivedAt: now, updatedAt: now }).where(eq(folders.id, id));
      const result = { ...current, state: action === 'delete' ? 'pending-deletion' : 'archived', ...(action === 'delete' ? { purgeAfter: purgeAfter.toISOString() } : {}) }; await tx.insert(operationReceipts).values({ accountId, idempotencyKey: input.idempotencyKey as string, entityType, entityId: id, action, result }); return result;
    }, { isolationLevel: 'serializable' }));
  }
}
