import { Inject, Injectable } from '@nestjs/common';
import { and, eq, lte } from 'drizzle-orm';
import { createHash } from 'node:crypto';
import { Database } from '../../infrastructure/database/database.js';
import { resourceLinks, resources, resourceVersions } from '../../infrastructure/database/schema.js';
import { UploadQueue } from '../../infrastructure/queue/upload.queue.js';

@Injectable()
export class LinkRepository {
  constructor(@Inject(Database) private readonly database: Database, @Inject(UploadQueue) private readonly queue: UploadQueue) {}
  async create(accountId: string, authorUserId: string, url: string, title: string) { const requestedAt = new Date(); return this.database.db.transaction(async tx => { const [resource] = await tx.insert(resources).values({ accountId, authorUserId, type: 'link', title, creationMethod: 'manual', updatedAt: requestedAt }).returning(); const [version] = await tx.insert(resourceVersions).values({ resourceId: resource!.id, authorUserId, ordinal: 1, content: url, contentHash: createHash('sha256').update(url).digest('hex'), mediaType: 'text/uri-list' }).returning(); await tx.update(resources).set({ currentVersionId: version!.id }).where(eq(resources.id, resource!.id)); await tx.insert(resourceLinks).values({ resourceId: resource!.id, url, metadataStatus: 'pending', requestedAt }); await this.queue.enqueueLink(resource!.id, requestedAt.toISOString(), tx); return this.get(accountId, resource!.id, tx); }); }
  async get(accountId: string, id: string, database: Pick<Database['db'], 'select'> = this.database.db) { const [row] = await database.select({ id: resources.id, accountId: resources.accountId, title: resources.title, description: resources.description, type: resources.type, updatedAt: resources.updatedAt, url: resourceLinks.url, previewImageUrl: resourceLinks.previewImageUrl, metadataStatus: resourceLinks.metadataStatus, requestedAt: resourceLinks.requestedAt }).from(resources).innerJoin(resourceLinks, eq(resourceLinks.resourceId, resources.id)).where(and(eq(resources.accountId, accountId), eq(resources.id, id), eq(resources.type, 'link'))).limit(1); return row; }
  async internal(id: string) { const [row] = await this.database.db.select({ id: resources.id, url: resourceLinks.url, requestedAt: resourceLinks.requestedAt }).from(resourceLinks).innerJoin(resources, eq(resources.id, resourceLinks.resourceId)).where(eq(resourceLinks.resourceId, id)).limit(1); return row; }
  async update(accountId: string, id: string, title: string, description: string | null) { const [row] = await this.database.db.update(resources).set({ title, description, updatedAt: new Date() }).where(and(eq(resources.accountId, accountId), eq(resources.id, id), eq(resources.type, 'link'))).returning(); return row ? this.get(accountId, id) : undefined; }
  async retry(accountId: string, id: string) { const requestedAt = new Date(); return this.database.db.transaction(async tx => { const [link] = await tx.update(resourceLinks).set({ metadataStatus: 'pending', metadataFailure: null, requestedAt, updatedAt: requestedAt }).from(resources).where(and(eq(resourceLinks.resourceId, id), eq(resources.id, id), eq(resources.accountId, accountId), eq(resources.type, 'link'))).returning({ id: resourceLinks.resourceId }); if (!link) return; await this.queue.enqueueLink(id, requestedAt.toISOString(), tx); return this.get(accountId, id, tx); }); }
  async complete(id: string, requestedAt: Date, metadata: { title?: string; description?: string; previewImageUrl?: string }) { await this.database.db.transaction(async tx => { const [current] = await tx.update(resourceLinks).set({ metadataStatus: 'ready', metadataFailure: null, previewImageUrl: metadata.previewImageUrl ?? null, updatedAt: new Date() }).where(and(eq(resourceLinks.resourceId, id), eq(resourceLinks.requestedAt, requestedAt))).returning(); if (!current) return; const changes: { updatedAt: Date; title?: string; description?: string } = { updatedAt: new Date() }; if (metadata.title) changes.title = metadata.title; if (metadata.description) changes.description = metadata.description; await tx.update(resources).set(changes).where(and(eq(resources.id, id), lte(resources.updatedAt, requestedAt))); }); }
  async fail(id: string, requestedAt: Date, reason: string) { await this.database.db.update(resourceLinks).set({ metadataStatus: 'failed', metadataFailure: reason, updatedAt: new Date() }).where(and(eq(resourceLinks.resourceId, id), eq(resourceLinks.requestedAt, requestedAt))); }
}
