import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { ResourceRepository } from './resource.repository.js';
import { UPLOAD_STORAGE, type UploadStorage } from '../uploads/upload.ports.js';

function decodeCursor(value?: string): [Date, string] | undefined { if (!value) return; try { const [dateValue, id] = JSON.parse(Buffer.from(value, 'base64url').toString()) as [string, string]; const date = new Date(dateValue); if (!id || Number.isNaN(date.getTime())) throw new Error(); return [date, id]; } catch { throw new BadRequestException('El cursor no es válido.'); } }
function encodeCursor(value: { updatedAt: Date; id: string }) { return Buffer.from(JSON.stringify([value.updatedAt.toISOString(), value.id])).toString('base64url'); }

@Injectable()
export class ResourceService {
  constructor(@Inject(ResourceRepository) private readonly repository: ResourceRepository, @Inject(UPLOAD_STORAGE) private readonly storage: UploadStorage) {}
  private view(resource: NonNullable<Awaited<ReturnType<ResourceRepository['get']>>>) { const accessibilityRequired = resource.type === 'file' && /^(image|audio|video)\//.test(resource.mediaType ?? ''); return { id: resource.id, title: resource.title, description: resource.description, aliases: resource.aliases, tags: resource.tags, properties: resource.properties, versionId: resource.versionId, type: resource.type, mediaType: resource.mediaType, byteSize: resource.byteSize, origin: resource.type === 'file' ? 'Carga desde dispositivo' : resource.type === 'link' ? resource.url! : 'Creación manual', status: resource.archivedAt ? 'archived' as const : 'ready' as const, archivedAt: resource.archivedAt, updatedAt: resource.updatedAt, libraryFolderId: resource.libraryFolderId, content: resource.type === 'note' ? resource.content : undefined, url: resource.url, previewImageUrl: resource.previewImageUrl, metadataStatus: resource.metadataStatus, accessibilityText: resource.accessibilityText, accessibilityRequired, accessibilityMissing: accessibilityRequired && !resource.accessibilityText?.trim() }; }
  async list(accountId: string, input: { type?: string; status?: string; cursor?: string; query?: string; tag?: string; projectId?: string; folderId?: string; libraryFolderId?: string } = {}) { if (input.type && !['note', 'file', 'link'].includes(input.type)) throw new BadRequestException('El tipo de recurso no es válido.'); if (input.status && !['active', 'archived'].includes(input.status)) throw new BadRequestException('El estado no es válido.'); const query = input.query?.trim(); if (query && query.length > 160) throw new BadRequestException('La búsqueda debe tener hasta 160 caracteres.'); const tag = input.tag?.trim(); if (tag && !/^[\p{L}\p{N}_/-]{1,80}$/u.test(tag)) throw new BadRequestException('La etiqueta no es válida.'); const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; if ((input.projectId && !uuid.test(input.projectId)) || (input.folderId && !uuid.test(input.folderId)) || (input.libraryFolderId && input.libraryFolderId !== 'root' && !uuid.test(input.libraryFolderId))) throw new BadRequestException('El filtro no es válido.'); if (input.folderId && !input.projectId) throw new BadRequestException('Selecciona un proyecto para filtrar por carpeta.'); const rows = await this.repository.list(accountId, { type: input.type as 'note' | 'file' | 'link' | undefined, status: input.status === 'archived' ? 'archived' : 'active', query, tag, projectId: input.projectId, folderId: input.folderId, libraryFolderId: input.libraryFolderId, cursor: decodeCursor(input.cursor) }); const data = rows.slice(0, 20).map(row => this.view(row)); return { data, meta: { nextCursor: rows.length > 20 ? encodeCursor(rows[19]!) : null } }; }
  async get(accountId: string, id: string) { const resource = await this.repository.get(accountId, id); if (!resource) throw new NotFoundException('Recurso no encontrado.'); return this.view(resource); }
  async access(accountId: string, id: string, modeValue?: string) { const resource = await this.repository.get(accountId, id); if (!resource?.storageKey || resource.type !== 'file') throw new NotFoundException('Archivo no encontrado.'); const mode = modeValue === 'download' ? 'download' : 'inline'; return { url: await this.storage.presignGet(resource.storageKey, resource.title, mode), expiresIn: 300, mode }; }
  async setAccessibility(accountId: string, id: string, value: unknown) { if (typeof value !== 'string' || value.length > 2000) throw new BadRequestException('La información de accesibilidad debe tener hasta 2000 caracteres.'); const resource = await this.repository.setAccessibility(accountId, id, value.trim()); if (!resource) throw new NotFoundException('Recurso no encontrado.'); return this.view(resource); }
  async renameFile(accountId: string, id: string, titleValue: unknown, updatedAtValue: unknown) { const title = typeof titleValue === 'string' ? titleValue.trim() : ''; if (!title || title.length > 160 || title.includes('/') || title.includes('\\') || [...title].some(character => character.charCodeAt(0) < 32)) throw new BadRequestException('Usa un nombre de archivo de 1 a 160 caracteres, sin barras ni caracteres de control.'); const expectedUpdatedAt = typeof updatedAtValue === 'string' ? new Date(updatedAtValue) : new Date(NaN); if (Number.isNaN(expectedUpdatedAt.getTime())) throw new BadRequestException('La versión del archivo no es válida.'); const current = await this.repository.get(accountId, id); if (!current || current.type !== 'file') throw new NotFoundException('Archivo no encontrado.'); if (current.updatedAt.getTime() !== expectedUpdatedAt.getTime()) throw new ConflictException('El archivo cambió. Vuelve a abrirlo antes de renombrarlo.'); const renamed = await this.repository.renameFile(accountId, id, title, expectedUpdatedAt); if (!renamed) throw new ConflictException('El archivo cambió. Vuelve a abrirlo antes de renombrarlo.'); return this.view(renamed); }
  async restore(accountId: string, id: string) { const resource = await this.repository.restore(accountId, id); if (!resource) throw new NotFoundException('Recurso no encontrado.'); return this.view(resource); }
}
