import { Inject, Injectable } from '@nestjs/common';
import { and, desc, eq, exists, ilike, isNotNull, isNull, lt, or } from 'drizzle-orm';
import { Database } from '../../infrastructure/database/database.js';
import { projectResources, resourceAccessibility, resourceLinks, resources, resourceVersions } from '../../infrastructure/database/schema.js';

@Injectable()
export class ResourceRepository {
  constructor(@Inject(Database) private readonly database: Database) {}
  private selection = { id: resources.id, title: resources.title, description: resources.description, type: resources.type, creationMethod: resources.creationMethod, archivedAt: resources.archivedAt, updatedAt: resources.updatedAt, versionId: resourceVersions.id, content: resourceVersions.content, storageKey: resourceVersions.storageKey, mediaType: resourceVersions.mediaType, byteSize: resourceVersions.byteSize, accessibilityText: resourceAccessibility.text, url: resourceLinks.url, previewImageUrl: resourceLinks.previewImageUrl, metadataStatus: resourceLinks.metadataStatus };
  async list(accountId: string, filters: { type?: 'note' | 'file' | 'link'; status?: 'active' | 'archived'; query?: string; projectId?: string; folderId?: string; cursor?: [Date, string] }) { const page = filters.cursor ? or(lt(resources.updatedAt, filters.cursor[0]), and(eq(resources.updatedAt, filters.cursor[0]), lt(resources.id, filters.cursor[1]))) : undefined; const placement = filters.projectId ? exists(this.database.db.select({ id: projectResources.id }).from(projectResources).where(and(eq(projectResources.resourceId, resources.id), eq(projectResources.projectId, filters.projectId), filters.folderId ? eq(projectResources.folderId, filters.folderId) : undefined))) : undefined; const pattern = filters.query ? `%${filters.query.replace(/[\\%_]/g, '\\$&')}%` : undefined; return this.database.db.select(this.selection).from(resources).innerJoin(resourceVersions, eq(resourceVersions.id, resources.currentVersionId)).leftJoin(resourceAccessibility, eq(resourceAccessibility.resourceId, resources.id)).leftJoin(resourceLinks, eq(resourceLinks.resourceId, resources.id)).where(and(eq(resources.accountId, accountId), isNull(resources.deletedAt), filters.status === 'archived' ? isNotNull(resources.archivedAt) : isNull(resources.archivedAt), filters.type ? eq(resources.type, filters.type) : undefined, pattern ? ilike(resources.title, pattern) : undefined, placement, page)).orderBy(desc(resources.updatedAt), desc(resources.id)).limit(21); }
  async get(accountId: string, id: string) { const [value] = await this.database.db.select(this.selection).from(resources).innerJoin(resourceVersions, eq(resourceVersions.id, resources.currentVersionId)).leftJoin(resourceAccessibility, eq(resourceAccessibility.resourceId, resources.id)).leftJoin(resourceLinks, eq(resourceLinks.resourceId, resources.id)).where(and(eq(resources.accountId, accountId), eq(resources.id, id), isNull(resources.deletedAt))).limit(1); return value; }
  async setAccessibility(accountId: string, id: string, text: string) { const resource = await this.get(accountId, id); if (!resource) return; await this.database.db.insert(resourceAccessibility).values({ resourceId: id, text }).onConflictDoUpdate({ target: resourceAccessibility.resourceId, set: { text, updatedAt: new Date() } }); return this.get(accountId, id); }
  async restore(accountId: string, id: string) { const [resource] = await this.database.db.update(resources).set({ archivedAt: null, updatedAt: new Date() }).where(and(eq(resources.accountId, accountId), eq(resources.id, id), isNull(resources.deletedAt))).returning(); return resource ? this.get(accountId, id) : undefined; }
}
