import { Inject, Injectable } from '@nestjs/common';
import { UploadRepository } from './upload.repository.js';
import { MALWARE_SCANNER, UPLOAD_STORAGE, type MalwareScanner, type UploadStorage } from './upload.ports.js';

const office = new Set(['application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.oasis.opendocument.text', 'application/octet-stream']);
const expectedByExtension: Record<string, string[]> = { txt: ['text/plain'], md: ['text/plain'], pdf: ['application/pdf'], jpg: ['image/jpeg'], jpeg: ['image/jpeg'], png: ['image/png'], webp: ['image/webp'], gif: ['image/gif'], mp3: ['audio/mpeg'], m4a: ['video/mp4'], aac: ['video/mp4'], ogg: ['audio/ogg'], wav: ['audio/wav'], mp4: ['video/mp4'], webm: ['video/webm'], doc: ['application/octet-stream'], xls: ['application/octet-stream'], ppt: ['application/octet-stream'], docx: ['application/zip'], xlsx: ['application/zip'], pptx: ['application/zip'], odt: ['application/zip'] };
export function mediaTypesMatch(declared: string, detected: string, name = '') { if (declared === 'application/octet-stream') return expectedByExtension[name.split('.').pop()?.toLowerCase() ?? '']?.includes(detected) ?? false; if (declared === detected) return true; if (declared === 'text/markdown' && detected === 'text/plain') return true; if (declared === 'audio/x-wav' && detected === 'audio/wav') return true; if (['audio/mp4', 'audio/aac'].includes(declared) && detected === 'video/mp4') return true; return office.has(declared) && ['application/zip', 'application/octet-stream'].includes(detected); }

@Injectable()
export class UploadProcessor {
  constructor(@Inject(UploadRepository) private readonly repository: UploadRepository, @Inject(UPLOAD_STORAGE) private readonly storage: UploadStorage, @Inject(MALWARE_SCANNER) private readonly scanner: MalwareScanner) {}
  async process(id: string) { const upload = await this.repository.claimScan(id); if (!upload?.snapshotKey) return; const result = await this.scanner.scan(await this.storage.read(upload.snapshotKey)); if (!result.clean) { await this.repository.setFailure(id, 'rejected', `El análisis antimalware rechazó el archivo: ${result.signature ?? 'amenaza detectada'}.`); await this.storage.remove(upload.snapshotKey).catch(() => undefined); return; } if (!mediaTypesMatch(upload.declaredMediaType, result.detectedMediaType, upload.originalName)) { await this.repository.setFailure(id, 'rejected', 'El tipo real del archivo no coincide con el declarado.'); await this.storage.remove(upload.snapshotKey).catch(() => undefined); return; } const cleanKey = `clean/${upload.accountId}/${upload.resourceId}/${result.sha256}`; await this.storage.copy(upload.snapshotKey, cleanKey); const clean = await this.storage.head(cleanKey); if (clean.size !== upload.declaredSize) throw new Error('La promoción del objeto no conservó su tamaño.'); await this.repository.ready(id, { sha256: result.sha256, detectedMediaType: result.detectedMediaType, cleanKey }); await this.storage.remove(upload.snapshotKey).catch(() => undefined); }
  async exhausted(id: string) { const upload = await this.repository.getInternal(id); if (upload?.snapshotKey) await this.storage.remove(upload.snapshotKey).catch(() => undefined); await this.repository.setFailure(id, 'failed', 'El análisis seguro no pudo completarse. Puedes reintentar la carga.'); }
}
