import { Module } from '@nestjs/common';
import { Database } from './infrastructure/database/database.js';
import { ClerkAuthGuard } from './infrastructure/auth/clerk-auth.guard.js';
import { AccountService } from './modules/account/account.service.js';
import { HealthController } from './interfaces/http/health.controller.js';
import { MeController } from './interfaces/http/me.controller.js';
import { ClerkWebhookController } from './interfaces/http/clerk-webhook.controller.js';
import { ProjectsController } from './interfaces/http/projects.controller.js';
import { ProjectService } from './modules/projects/project.service.js';
import { NotesController } from './interfaces/http/notes.controller.js';
import { NoteService } from './modules/resources/note.service.js';
import { OrganizationController } from './interfaces/http/organization.controller.js';
import { OrganizationService } from './modules/projects/organization.service.js';
import { UploadsController } from './interfaces/http/uploads.controller.js';
import { UploadService } from './modules/uploads/upload.service.js';
import { UploadProcessor } from './modules/uploads/upload.processor.js';
import { UploadRepository } from './modules/uploads/upload.repository.js';
import { UploadQueue } from './infrastructure/queue/upload.queue.js';
import { S3UploadStorage } from './infrastructure/storage/s3-upload.storage.js';
import { ClamAvScanner } from './infrastructure/security/clamav.scanner.js';
import { MALWARE_SCANNER, UPLOAD_STORAGE } from './modules/uploads/upload.ports.js';
import { ResourcesController } from './interfaces/http/resources.controller.js';
import { ResourceService } from './modules/resources/resource.service.js';
import { ResourceRepository } from './modules/resources/resource.repository.js';
@Module({ controllers: [HealthController, MeController, ClerkWebhookController, ProjectsController, NotesController, OrganizationController, UploadsController, ResourcesController], providers: [Database, ClerkAuthGuard, AccountService, ProjectService, NoteService, ResourceService, ResourceRepository, OrganizationService, UploadService, UploadProcessor, UploadRepository, UploadQueue, S3UploadStorage, ClamAvScanner, { provide: UPLOAD_STORAGE, useExisting: S3UploadStorage }, { provide: MALWARE_SCANNER, useExisting: ClamAvScanner }] }) export class AppModule {}
